### ISSUE TITLE
MetadataWidget needs refactoring due to multiple issues

### ISSUE THREAD

**Issue by jusa3** [nfdi4health/semlookp-widgets#30]
It is possible to work on the following tasks in parallel:
- [x] error handling see also #31 
- [x] querying only once and pass data as props to sub-widgets for better performance?
- [x] ontologyId parameter optional (with always showing defining terminology and if not available the first ontology with a hint for the user) see #18 
- [x] entityType parameter optional (with entities endpoint of ols4/v2 API) - can it be done with the ols3 API and a default entityType?

All widgets (except entity relations and hierarchy) must run with the ols3 API. The ols4 API can be used (and has to be used? for optional entityType parameter) but backwards compatibility must be guaranteed. Means, there must be a conditional and corresponding documentation when using the ols4 API.

**Comment by VincentKneip** [comment]
Regarding the second task: HierarchyWidget uses other api responses than the other two. But the Widget was to be redesigned anyway, right?

**Comment by jusa3** [comment]
Oh you're right, the HierarchyWidget must be excluded from this changes. It is independent from the other sub widgets.

**Comment by VincentKneip** [comment]
Pushed a [commit](https://github.com/nfdi4health/semlookp-widgets/commit/65a8ef80443d57b590e4c54595a79b1c86689b20) in which ontologyId parameters are optional. If not provided, the defining ontology is searched and selected if existent:
 
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/114bcdb3-3a80-467c-af17-8f38800fe9c8)

Otherwise, the first ontology available is selected and a message for the user is shown:

![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/645a91c4-79b1-4c75-8984-b07a4ea12cd5)

The examples are added to Storybook, so you can have a look yourself.

**Questions:**
- Is the functionality/look as expected @jusa3?
- To fetch the defining ontology, an additional api request is needed inside MetadataWidget. Is that convenient?
- Should the same thing also be done for the individual widgets inside MetadataWidget (Iri-, Description-, Breadcrumb-, Tabwidget)? If so, every widget would have to fetch this additional api request because we otherwise get the same problem of having to pass the request's state variables `isLoading`, `isSuccess` etc. to the child widgets which does not work well

**Comment by jusa3** [comment]
- Looks good. Maybe select another color for the info message because red is alerting (maybe black and cursive?). 
- Yes, I don't see any other solution for this right now. 
- Yes, but mabe you can combine it with the the requests needed for the other information (maybe the defining ontology info comes along).

**Comment by VincentKneip** [comment]
Adjusted the look of the info message: 
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/9dd94234-da96-4a4f-a48f-d28893a2c603)

Also made the ontologyId parameter optional for [Breadcrumb-](https://github.com/nfdi4health/semlookp-widgets/commit/0807a5659a3d4015634b340af441fe3d54971463#diff-0c8947eb5926764bbe353b98f33b1ef74386f144513bd84727a4766014b31fbc), [Title-](https://github.com/nfdi4health/semlookp-widgets/commit/0807a5659a3d4015634b340af441fe3d54971463#diff-fad82ad527407288717458fb6eaad5dcb0349a36f90cbd3a13b4246c8be31842) and [DescriptionWidget](https://github.com/nfdi4health/semlookp-widgets/commit/0807a5659a3d4015634b340af441fe3d54971463#diff-6d073177bf1a682d23d848a236605cdccb0aae07e16a536615d1fab85e2ff0a9). TabWidget and children still need to be done.

Do we want to include the info message on every child widget of MetadataWidget? It currently is, and looks like this:
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/08d13f8c-2fdf-4ae7-b3de-6d7d248e0758)
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/4f85cd1d-c5a0-4a97-b75e-c1b3508a4779)
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/3db8f3e3-0049-4f27-be12-81c0f7e5ff8f)

**Comment by VincentKneip** [comment]
[TabWidget](https://github.com/nfdi4health/semlookp-widgets/commit/964e30fb47db3ff05e8caf74fb71ad2df6ef787c), [AlternativeNameTabWidget and CrossRefTabWidget](https://github.com/nfdi4health/semlookp-widgets/commit/5f4dc657cc9e85d0b2d544bab285ec24356af32c) feature optional ontologyId parameters and info messages if defining ontology is not available now as well.

**Comment by VincentKneip** [comment]
That's already the case!

The info message is only displayed when no ontologyId is provided as widget property. Therefore, to bypass the message being displayed multiple times, and to optimize request efficiency, a parent widget passes the ontologyId (either the one already provided or if no id is provided, the defining ontology or first available other ontology) to all its child widgets.

**Comment by johannes-darms** [comment]
The information message about a missing ontology is shown to an end user, who cannot add the missing property. Hence, the message recipient cannot use the information. Maybe, we could log the missing property message such that a developer is aware of a possible improvement/bug and show a more subtle information to the end-user.

**Comment by VincentKneip** [comment]
The information message has been removed by now. As the defining ontology not being available and showing occurrences in other ontologies is actually not a real issue, the error message has been removed entirely, also not logging it to the console. This is because the set of ontologies is strictly limited in most cases, especially when applying a specific set of ontologies using the _parameter_ property

**Comment by VincentKneip** [comment]
All the tasks mentioned in the first comment are implemented by now. Therefore, I think we can close this issue. A further discussion of the error handling and messages shown is to be held in the future
