### ISSUE TITLE
partly implemented/none/not consistent error handling

### ISSUE THREAD

**Issue by jusa3** [nfdi4health/semlookp-widgets#31]
We need error handling in all widgets if the request can't be resolved because of
- ERROR (wrong parameters/IRI not available in SemLookP etc.): https://semanticlookup.zbmed.de/api/ontologies/mesh/terms?iri=http:%2F%2Fid.nlm.nih.gov%2Fmesh%2FD000086382
- EMPTY RESPONSE: https://semanticlookup.zbmed.de/ols/api/terms/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C654654

Partly resolved in #22 - should be an event and specific error messages, not an option for the users to render their own error messages

**Comment by VincentKneip** [comment]
Would it be an option to throw the errors directly in the respective functions in `OlsApi.ts` and to catch them via `isError` and `error` return values of `useQuery()`?

**Comment by VincentKneip** [comment]
The event should probably give more specific information on the error than the message displayed inside the widget, something like this:
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/eb736117-c297-4abf-926b-7c1b1cc0f409)

Therefore, I suggest creating a global method residing in `widgets/index.ts` or a new file (e.g. `widgets/utilities.ts`)which maps specific error messages to error message for display inside the widgets, which can be called with `error` as parameter if `isError === true`. Taking a legacy parameter into consideration, distinguishing between using ols3 and ols4, the displayed message could also give a hint that the legacy parameter value might be wrong. What do you think of these ideas @jusa3?

Are there any other special events for displayed messages?

**Comment by jusa3** [comment]
Sounds good to me. I can't think of any other scenarious right now. It is possible, that we have to add some more later, but this should be no problem with your approach.
If the request url is not valid (e.g. https://semanticlookup.zbmed.de/ols/api/bdfg) there is an error, but this should be catched by Axios.

**Comment by VincentKneip** [comment]
Implemented distinction between empty response (done by checking `response["page"]["totalElements"] === 0`)
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/f15f9904-1c01-4505-a6dc-c40e4df0989a)
and general error
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/cf253ce2-eee9-425e-91b7-0d868ef38beb)

Also added error thrown for `https://semanticlookup.zbmed.de/api/` which otherwise just returns a json containing the error:

![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/3ad5b58f-fe77-479a-b4de-552207437ae2)
![grafik](https://github.com/nfdi4health/semlookp-widgets/assets/141128943/01062489-54c0-429d-a801-5ae010b4a023)
