### ISSUE TITLE
de-selects of autocomplete widget

### ISSUE THREAD

**Issue by cllde8** [nfdi4health/semlookp-widgets#43]
Hi,

Thanks for the great work on the widgets; they look quite nice. I tried the "Autocomplete Widget" during Hackathons and had a conversation with Roman. I would like to share my findings.

During testing, I observed that the `selectionChangedEvent` is not triggered when the user de-selects/clears an option. I am curious to know what plans are in place to address this behavior. It would be great to have a solution or workaround for such scenarios.

Thank you.
Claire

**Comment by VincentKneip** [comment]
Hey Claire,

thank you for your suggestion!

It turns out that the `selectionChangedEvent` was only fired if there are any `selectedOptions` (see [here](https://github.com/nfdi4health/semlookp-widgets/blob/92caf93081fb986f776f569152d7af71376b9bee/src/components/widgets/AutocompleteWidget/AutocompleteWidget.tsx#L264)), and that the `selectedOptions` were only updated internally if the search value in the `AutocompleteWidget` was of length > 0 (see [here](https://github.com/nfdi4health/semlookp-widgets/blob/92caf93081fb986f776f569152d7af71376b9bee/src/components/widgets/AutocompleteWidget/AutocompleteWidget.tsx#L229)). 

Having fixed this, the `selectionChangedEvent` is now also triggered if the options are cleared.
